--VERSION:1.1-beta
--CHANGELOG_START
- Perbaikan bug saat navigasi Node
- Optimasi pemakaian baterai Jieshuo
- Penambahan fungsi API baru
--CHANGELOG_END
【Informasi Class】
com.androlua.LuaApplication
【Superclass】
android.app.Application
【Interfaces】
com.androlua.LuaContext
【Metode Konstruksi】
public com.androlua.LuaApplication()
【Bidang (Field)】
【Metode】
public native void com.androlua.LuaApplication.call(java.lang.String,java.lang.Object[])
public native java.lang.String com.androlua.LuaApplication.callStringFunction(java.lang.String,java.lang.Object[])
public native boolean com.androlua.LuaApplication.checkInfo()
public final native boolean com.androlua.LuaApplication.checkVip()
public native void com.androlua.LuaApplication.clearAllActivity()
public native void com.androlua.LuaApplication.clearAndExit()
public native java.lang.Object com.androlua.LuaApplication.doAsset(java.lang.String,java.lang.Object[])
public native java.lang.Object com.androlua.LuaApplication.doFile(java.lang.String,java.lang.Object[])
public native java.lang.Object com.androlua.LuaApplication.get(java.lang.String)
public native java.util.ArrayList com.androlua.LuaApplication.getAllApp()
public static native java.util.ArrayList com.androlua.LuaApplication.getAppList()
public native java.lang.String com.androlua.LuaApplication.getBackupDir()
public native java.util.ArrayList com.androlua.LuaApplication.getClassLoaders()
public native java.lang.String com.androlua.LuaApplication.getCmdDir()
public native java.lang.String com.androlua.LuaApplication.getCmdPath(java.lang.String)
public native android.content.Context com.androlua.LuaApplication.getContext()
public native java.lang.String com.androlua.LuaApplication.getDeLuaPath(java.lang.String)
public native java.lang.String com.androlua.LuaApplication.getDownloadDir()
public native java.lang.String com.androlua.LuaApplication.getDownloadPath(java.lang.String)
public static native java.lang.String com.androlua.LuaApplication.getFileName(java.lang.String,java.lang.String)
public native java.lang.String com.androlua.LuaApplication.getGesturePath(java.lang.String,java.lang.String)
public native java.lang.String com.androlua.LuaApplication.getGesturesDir()
public native java.lang.String com.androlua.LuaApplication.getGesturesDir(java.lang.String)
public native java.util.Map com.androlua.LuaApplication.getGlobalData()
public native int com.androlua.LuaApplication.getHeight()
public native java.lang.String com.androlua.LuaApplication.getHelpersDir()
public native java.lang.String com.androlua.LuaApplication.getHelpersDir(java.lang.String)
public native java.lang.String com.androlua.LuaApplication.getHelpersPath(java.lang.String,java.lang.String)
public native java.lang.String com.androlua.LuaApplication.getHotKeysDir()
public native java.lang.String com.androlua.LuaApplication.getHotKeysDir(java.lang.String)
public native java.lang.String com.androlua.LuaApplication.getHotKeysPath(java.lang.String,java.lang.String)
public native java.lang.String com.androlua.LuaApplication.getId()
public static native com.androlua.LuaApplication com.androlua.LuaApplication.getInstance()
public native java.lang.String com.androlua.LuaApplication.getLabelsDir()
public native java.lang.String com.androlua.LuaApplication.getLabelsDir(java.lang.String)
public native java.lang.String com.androlua.LuaApplication.getLibDir()
public native java.util.HashMap com.androlua.LuaApplication.getLibrarys()
public native java.lang.String com.androlua.LuaApplication.getLocalDir()
public native java.lang.String com.androlua.LuaApplication.getLuaCpath()
public native java.lang.String com.androlua.LuaApplication.getLuaDir()
public native java.lang.String com.androlua.LuaApplication.getLuaDir(java.lang.String)
public native java.lang.String com.androlua.LuaApplication.getLuaExtDir()
public native java.lang.String com.androlua.LuaApplication.getLuaExtDir(java.lang.String)
public native java.lang.String com.androlua.LuaApplication.getLuaExtPath(java.lang.String)
public native java.lang.String com.androlua.LuaApplication.getLuaExtPath(java.lang.String,java.lang.String)
public native java.lang.String com.androlua.LuaApplication.getLuaLpath()
public native java.lang.String com.androlua.LuaApplication.getLuaPath()
public native java.lang.String com.androlua.LuaApplication.getLuaPath(java.lang.String)
public native java.lang.String com.androlua.LuaApplication.getLuaPath(java.lang.String,java.lang.String)
public native com.luajava.LuaState com.androlua.LuaApplication.getLuaState()
public native java.lang.String com.androlua.LuaApplication.getMdDir()
public native java.lang.String com.androlua.LuaApplication.getNamesDir()
public native java.lang.String com.androlua.LuaApplication.getNamesPath(java.lang.String)
public native java.lang.String com.androlua.LuaApplication.getNaviDir()
public native java.lang.String com.androlua.LuaApplication.getNaviPath(java.lang.String)
public native java.lang.String com.androlua.LuaApplication.getNotesDir()
public native java.lang.String com.androlua.LuaApplication.getNotesPath(java.lang.String)
public native java.lang.String com.androlua.LuaApplication.getOdexDir()
public native java.lang.String com.androlua.LuaApplication.getPluginsDir()
public native java.lang.String com.androlua.LuaApplication.getPluginsDir(java.lang.String)
public native java.lang.String com.androlua.LuaApplication.getPluginsPath(java.lang.String,java.lang.String)
public native android.content.res.Resources com.androlua.LuaApplication.getResources()
public native java.lang.String com.androlua.LuaApplication.getResourcesDir()
public native java.lang.String com.androlua.LuaApplication.getResourcesDir(java.lang.String)
public native java.lang.Object com.androlua.LuaApplication.getSharedData(java.lang.String)
public native java.lang.Object com.androlua.LuaApplication.getSharedData(java.lang.String,java.lang.Object)
public native android.content.SharedPreferences com.androlua.LuaApplication.getSharedPreferences(java.lang.String,int)
public native java.lang.String com.androlua.LuaApplication.getSoundsDir()
public native java.lang.String com.androlua.LuaApplication.getSoundsDir(java.lang.String)
public native java.lang.Object com.androlua.LuaApplication.getSystemService(java.lang.String)
public native java.lang.String com.androlua.LuaApplication.getTimerDir()
public native java.lang.String com.androlua.LuaApplication.getTimerPath(java.lang.String)
public native java.lang.String com.androlua.LuaApplication.getToolsDir()
public native java.lang.String com.androlua.LuaApplication.getToolsDir(java.lang.String)
public native android.net.Uri com.androlua.LuaApplication.getUriForFile(java.io.File)
public native android.net.Uri com.androlua.LuaApplication.getUriForPath(java.lang.String)
public native java.lang.String com.androlua.LuaApplication.getUserId(java.lang.String)
public native java.lang.String com.androlua.LuaApplication.getUserName(java.lang.String)
public native int com.androlua.LuaApplication.getWidth()
public native boolean com.androlua.LuaApplication.inJieshuoActivity()
public final native void com.androlua.LuaApplication.init()
public final native boolean com.androlua.LuaApplication.isAbc()
public final native boolean com.androlua.LuaApplication.isVip()
public native void com.androlua.LuaApplication.onCreate()
public native byte[] com.androlua.LuaApplication.readAsset(java.lang.String)
public native void com.androlua.LuaApplication.regGc(com.androlua.LuaGcable)
public native android.content.Intent com.androlua.LuaApplication.registerReceiver(android.content.BroadcastReceiver,android.content.IntentFilter)
public native android.content.Intent com.androlua.LuaApplication.registerReceiver(android.content.BroadcastReceiver,android.content.IntentFilter,int)
public native android.content.Intent com.androlua.LuaApplication.registerReceiver(android.content.BroadcastReceiver,android.content.IntentFilter,java.lang.String,android.os.Handler)
public native android.content.Intent com.androlua.LuaApplication.registerReceiver(android.content.BroadcastReceiver,android.content.IntentFilter,java.lang.String,android.os.Handler,int)
public native void com.androlua.LuaApplication.sendError(java.lang.String,java.lang.Exception)
public native void com.androlua.LuaApplication.sendMsg(java.lang.String)
public native void com.androlua.LuaApplication.set(java.lang.String,java.lang.Object)
public static native void com.androlua.LuaApplication.setAppList(java.util.ArrayList)
public native void com.androlua.LuaApplication.setDebug(boolean)
public native boolean com.androlua.LuaApplication.setSharedData(java.lang.String,java.lang.Object)
public native void com.androlua.LuaApplication.setVip(boolean)
public native void com.androlua.LuaApplication.updateAllActivity()
